package chat

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/gorilla/websocket"
)

// ─────────────────────────────────────────────────────────────────────────────
// MUX Wire Formats
// ─────────────────────────────────────────────────────────────────────────────

// MuxInbound is the envelope the API Server sends to the Chat Server.
//
// Key fields:
//   - conn_id  — unique per device/connection (generated by API Server).
//     Used to distinguish Alice's Phone from Alice's Laptop.
//     If omitted, Chat Server auto-generates one (single-device mode).
//   - user_id  — the user (same across all devices for one person).
//
// Wire format:
//
//	{
//	  "conn_id":    "phone-abc123",      ← unique per client WS connection
//	  "user_id":    "alice-001",         ← which user (may have multiple devices)
//	  "user_name":  "Alice",
//	  "user_photo": "https://...",
//	  "data": {
//	    "type":      "text",
//	    "target_id": "bob-002",
//	    "is_group":  false,
//	    "content":   "Hello Bob!"
//	  }
//	}
type MuxInbound struct {
	ConnID    string          `json:"conn_id,omitempty"` // unique per device connection
	UserID    string          `json:"user_id"`           // required
	UserName  string          `json:"user_name,omitempty"`
	UserPhoto string          `json:"user_photo,omitempty"`
	Data      IncomingMessage `json:"data"`
}

// MuxOutbound is the envelope the Chat Server sends back to the API Server.
//
// The API Server MUST route based on conn_id (not user_id) to reach the
// correct device. user_id is included for informational purposes.
//
// Wire format:
//
//	{
//	  "conn_id": "phone-abc123",   ← route to THIS specific device
//	  "user_id": "alice-001",      ← informational
//	  "kind":    "message",        ← "message" | "session"
//	  "data":    { ...Message... }
//	}
type MuxOutbound struct {
	ConnID string `json:"conn_id"` // which device connection to deliver to
	UserID string `json:"user_id"` // informational
	Kind   string `json:"kind"`    // "message" | "session"
	Data   any    `json:"data"`
}

// ─────────────────────────────────────────────────────────────────────────────
// muxGateway — represents ONE physical WS connection from an API Server node
// ─────────────────────────────────────────────────────────────────────────────

type muxGateway struct {
	id      string
	hub     *Hub
	conn    *websocket.Conn
	writeMu sync.Mutex // one writer at a time — prevents interleaved frames

	mu    sync.RWMutex
	conns map[string]bool // connIDs currently on this gateway

	logger *log.Logger
}

func newMuxGateway(hub *Hub, conn *websocket.Conn, logger *log.Logger) *muxGateway {
	return &muxGateway{
		id:     uuid.New().String(),
		hub:    hub,
		conn:   conn,
		conns:  make(map[string]bool),
		logger: logger,
	}
}

// deliver sends a frame to a specific device connection via this gateway.
func (gw *muxGateway) deliver(connID, userID, kind string, data any) error {
	frame := MuxOutbound{
		ConnID: connID,
		UserID: userID,
		Kind:   kind,
		Data:   data,
	}
	gw.writeMu.Lock()
	defer gw.writeMu.Unlock()
	gw.conn.SetWriteDeadline(time.Now().Add(writeWait))
	return gw.conn.WriteJSON(frame)
}

func (gw *muxGateway) addConn(connID string) {
	gw.mu.Lock()
	gw.conns[connID] = true
	gw.mu.Unlock()
}

func (gw *muxGateway) removeConn(connID string) {
	gw.mu.Lock()
	delete(gw.conns, connID)
	gw.mu.Unlock()
}

func (gw *muxGateway) connIDs() []string {
	gw.mu.RLock()
	defer gw.mu.RUnlock()
	ids := make([]string, 0, len(gw.conns))
	for id := range gw.conns {
		ids = append(ids, id)
	}
	return ids
}

// ─────────────────────────────────────────────────────────────────────────────
// RunMux — main loop for a gateway connection
// ─────────────────────────────────────────────────────────────────────────────

func (gw *muxGateway) runMux(ctx context.Context) {
	defer func() {
		connIDs := gw.connIDs()
		gw.hub.unregisterGateway(gw)
		gw.logger.Printf("[mux] gateway %s disconnected — removed %d device connections",
			gw.id[:8], len(connIDs))
	}()

	gw.conn.SetReadLimit(maxMessageSize)
	gw.conn.SetReadDeadline(time.Now().Add(pongWait))
	gw.conn.SetPongHandler(func(string) error {
		gw.conn.SetReadDeadline(time.Now().Add(pongWait))
		return nil
	})

	// Ping goroutine.
	go func() {
		ticker := time.NewTicker(pingPeriod)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				gw.writeMu.Lock()
				gw.conn.SetWriteDeadline(time.Now().Add(writeWait))
				err := gw.conn.WriteMessage(websocket.PingMessage, nil)
				gw.writeMu.Unlock()
				if err != nil {
					return
				}
			}
		}
	}()

	for {
		_, raw, err := gw.conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err,
				websocket.CloseGoingAway, websocket.CloseNormalClosure) {
				gw.logger.Printf("[mux] read error on gateway %s: %v", gw.id[:8], err)
			}
			return
		}

		// ── Log raw inbound frame (debug) ─────────────────────────────────────
		gw.logger.Printf("[mux] ← gateway %s raw: %s", gw.id[:8], string(raw))

		// ── Parse envelope ────────────────────────────────────────────────────
		var inbound MuxInbound
		if err := json.Unmarshal(raw, &inbound); err != nil {
			gw.logger.Printf("[mux] bad frame from gateway %s: %v", gw.id[:8], err)
			gw.sendError("", "", "invalid JSON: "+err.Error())
			continue
		}

		gw.logger.Printf("[mux] ← conn=%s user=%s type=%s target=%s",
			inbound.ConnID, inbound.UserID, inbound.Data.Type, inbound.Data.TargetID)

		// ── Validate required fields ──────────────────────────────────────────
		if inbound.UserID == "" {
			gw.logger.Printf("[mux] missing user_id from gateway %s", gw.id[:8])
			gw.sendError(inbound.ConnID, "", "user_id is required")
			continue
		}

		// Auto-generate conn_id if API Server didn't provide one (single-device mode).
		if inbound.ConnID == "" {
			inbound.ConnID = inbound.UserID
		}

		// ── Register device connection ────────────────────────────────────────
		gw.hub.registerMuxConn(inbound.ConnID, inbound.UserID,
			inbound.UserName, inbound.UserPhoto, gw)

		// ── Validate message payload ──────────────────────────────────────────
		msg := inbound.Data
		msg.UUID = inbound.UserID // trust the API Server's user_id
		if err := msg.Validate(); err != nil {
			gw.logger.Printf("[mux] invalid msg conn=%s user=%s: %v",
				inbound.ConnID, inbound.UserID, err)
			gw.sendError(inbound.ConnID, inbound.UserID, err.Error())
			continue
		}

		// ── Route through hub ─────────────────────────────────────────────────
		if client, ok := gw.hub.getMuxVirtualClient(inbound.ConnID); ok {
			gw.hub.handleIncoming(ctx, client, msg)
		}
	}
}

// sendError writes a JSON error frame back to the API Server.
// Format: { "conn_id": "...", "user_id": "...", "kind": "error", "data": { "err": "message" } }
func (gw *muxGateway) sendError(connID, userID, errMsg string) {
	frame := MuxOutbound{
		ConnID: connID,
		UserID: userID,
		Kind:   "error",
		Data:   map[string]string{"err": errMsg},
	}
	gw.writeMu.Lock()
	defer gw.writeMu.Unlock()
	gw.conn.SetWriteDeadline(time.Now().Add(writeWait))
	if err := gw.conn.WriteJSON(frame); err != nil {
		gw.logger.Printf("[mux] failed to send error frame: %v", err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Hub MUX methods
// ─────────────────────────────────────────────────────────────────────────────

// registerMuxConn creates or migrates a virtual client for a device connection.
// connID   = unique per device (phone ≠ laptop, even if same user)
// userID   = who the user is (may appear in multiple connIDs)
func (h *Hub) registerMuxConn(connID, userID, userName, userPhoto string, gw *muxGateway) {
	h.mu.Lock()
	defer h.mu.Unlock()

	// If this connID already exists on a different gateway, migrate it.
	if vc, ok := h.muxConns[connID]; ok {
		if oldGW, gwOK := h.muxGateways[connID]; gwOK && oldGW != gw {
			oldGW.removeConn(connID)
			close(vc.send)
			h.logger.Printf("[hub] mux: migrating conn=%s user=%s gw %s→%s",
				connID, userID, oldGW.id[:8], gw.id[:8])
		}
	}

	// Create new virtual client for this device connection.
	vc := &Client{
		hub:    h,
		conn:   nil, // no direct WS — gateway handles transport
		send:   make(chan any, sendBufferSize),
		user:   User{UUID: userID, Name: userName, PhotoURL: userPhoto},
		token:  connID, // reuse token field to store connID for routing
		logger: h.logger,
	}
	h.muxConns[connID] = vc
	h.muxGateways[connID] = gw

	// Add connID to userID's device list (if not already present).
	found := false
	for _, id := range h.userConns[userID] {
		if id == connID {
			found = true
			break
		}
	}
	if !found {
		h.userConns[userID] = append(h.userConns[userID], connID)
	}

	gw.addConn(connID)
	h.logger.Printf("[hub] mux: registered conn=%s user=%s devices=%d",
		connID, userID, len(h.userConns[userID]))

	// Drain virtual client's send channel → gateway WS.
	// Only start if this is a real (non-nil) WS connection (not unit tests).
	if gw.conn != nil {
		go h.drainMuxConn(connID, userID, vc, gw)
	}
}

// getMuxVirtualClient returns the virtual Client for a connID.
func (h *Hub) getMuxVirtualClient(connID string) (*Client, bool) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	c, ok := h.muxConns[connID]
	return c, ok
}

// unregisterGateway removes all device connections belonging to gw.
func (h *Hub) unregisterGateway(gw *muxGateway) {
	connIDs := gw.connIDs()
	h.mu.Lock()
	for _, connID := range connIDs {
		if vc, ok := h.muxConns[connID]; ok {
			userID := vc.user.UUID
			close(vc.send)
			delete(h.muxConns, connID)
			delete(h.muxGateways, connID)
			// Remove from user's device list.
			list := h.userConns[userID]
			updated := list[:0]
			for _, id := range list {
				if id != connID {
					updated = append(updated, id)
				}
			}
			if len(updated) == 0 {
				delete(h.userConns, userID)
			} else {
				h.userConns[userID] = updated
			}
		}
	}
	delete(h.gateways, gw.id)
	h.mu.Unlock()
}

// deliverToMuxUser fans out a message to ALL device connections for userID.
// Returns true if delivered to at least one device.
func (h *Hub) deliverToMuxUser(userID string, msg Message) bool {
	h.mu.RLock()
	connIDs := make([]string, len(h.userConns[userID]))
	copy(connIDs, h.userConns[userID])
	h.mu.RUnlock()

	delivered := false
	for _, connID := range connIDs {
		h.mu.RLock()
		vc, ok := h.muxConns[connID]
		h.mu.RUnlock()
		if !ok {
			continue
		}
		select {
		case vc.send <- msg:
			delivered = true
		default:
			// Buffer full — remove this device connection.
			h.logger.Printf("[hub] mux: conn=%s buffer full, disconnecting", connID)
			h.mu.Lock()
			close(vc.send)
			delete(h.muxConns, connID)
			delete(h.muxGateways, connID)
			// Remove from user's device list.
			list := h.userConns[userID]
			updated := list[:0]
			for _, id := range list {
				if id != connID {
					updated = append(updated, id)
				}
			}
			if len(updated) == 0 {
				delete(h.userConns, userID)
			} else {
				h.userConns[userID] = updated
			}
			h.mu.Unlock()
		}
	}
	return delivered
}

// drainMuxConn reads from a virtual client's send channel and writes
// each frame as a MuxOutbound on the gateway WS.
func (h *Hub) drainMuxConn(connID, userID string, vc *Client, gw *muxGateway) {
	for frame := range vc.send {
		kind := "message"
		if _, ok := frame.(map[string]string); ok {
			kind = "session"
		}
		if err := gw.deliver(connID, userID, kind, frame); err != nil {
			h.logger.Printf("[mux] deliver error conn=%s: %v", connID, err)
			return
		}
	}
}

// ConnectMux registers a multiplexed gateway WebSocket connection.
// The API Server calls /ws/mux (with X-API-Key); one physical connection
// can carry messages for many device connections simultaneously.
func (cm *ChatModule) ConnectMux(conn *websocket.Conn) {
	ctx := context.Background()
	gw := newMuxGateway(cm.hub, conn, cm.logger)

	cm.hub.mu.Lock()
	cm.hub.gateways[gw.id] = gw
	cm.hub.mu.Unlock()

	cm.slog.Info("mux gateway connected", "id", fmt.Sprintf("%s...", gw.id[:8]))

	gw.runMux(ctx) // blocks until gateway disconnects
}
